import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import logoSrc from '../assets/IMG_1472.PNG';

export const generateBusinessReport = async (userData, statsData, insightsData) => {
  const doc = jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Helper function to load image
  const loadImage = (src) => {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = reject;
      img.src = src;
    });
  };

  // 1. Header with Logo
  try {
    const img = await loadImage(logoSrc);
    doc.addImage(img, 'PNG', 15, 10, 30, 10);
  } catch (e) {
    console.warn('Could not add logo to PDF', e);
  }

  doc.setFontSize(20);
  doc.setTextColor(40);
  doc.text('Manufacturing System Business Report', 55, 18);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 15, 30);
  doc.text(`Generated by: ${userData?.name} (${userData?.role})`, 15, 35);

  // 2. Key Performance Indicators Section
  doc.setFontSize(16);
  doc.setTextColor(180, 0, 0);
  doc.text('Key Stats Summary', 15, 50);

  const statsRows = [
    ['Metric', 'Value'],
    ['Total Products', statsData?.stats?.total_products || '0'],
    ['Monthly Sales', statsData?.stats?.total_sales || '0'],
    ['Inventory Value', `$${statsData?.stats?.inventory_value?.toLocaleString() || '0'}`],
    ['Monthly Revenue', `$${statsData?.stats?.total_revenue?.toLocaleString() || '0'}`]
  ];

  autoTable(doc, {
    startY: 55,
    head: [statsRows[0]],
    body: statsRows.slice(1),
    theme: 'striped',
    headStyles: { fillColor: [180, 0, 0] }
  });

  // 3. AI Insights Section
  let finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(16);
  doc.setTextColor(180, 0, 0);
  doc.text('Top AI Insights', 15, finalY);

  const insightRows = insightsData?.map(insight => [
    insight.priority.toUpperCase(),
    insight.title,
    insight.impact || 'N/A'
  ]) || [['N/A', 'No active insights', 'N/A']];

  autoTable(doc, {
    startY: finalY + 5,
    head: [['Priority', 'Insight Description', 'Potential Impact']],
    body: insightRows,
    theme: 'grid',
    headStyles: { fillColor: [50, 50, 50] },
    columnStyles: {
      0: { cellWidth: 30 },
      2: { cellWidth: 40 }
    }
  });

  // 4. Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} - Confidential Business Document`, pageWidth / 2, 285, { align: 'center' });
  }

  // Save the PDF
  doc.save(`Manufacturing_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
